version: '3.9'
services:
  server:
    platform: linux/amd64
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - 9000:9000
  client:
    platform: linux/amd64
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
